### ISSUE TITLE
 Preference category GSL is unregistered.

### ISSUE THREAD

**Issue by xdzhangxuejun** [brian-team/brian2#937] opened 2018-04-19 02:30 UTC
I can't import brian2. I get The error message is "Preference category GSL is unregistered."
my OP is ubuntu 14.2.

**Comment by mstimberg** [comment] 2018-04-19 09:38
This can happen if you have previously installed a recent version of Brian 2 (version >= 2.1) and now are trying to import an older version directly from source, without installation. The exact fix depends on the details of how you installed things (e.g. with `pip`?) As a quick solution, you can delete the `default_preferences` file that is generated during installation (but not necessary for using Brian). E.g. search for it via:
```console
$ locate brian2/default_preferences
```

**Comment by xdzhangxuejun** [comment] 2018-04-22 12:09
Thank you very much.






At 2018-04-19 17:38:40, "Marcel Stimberg" <notifications@github.com> wrote:


This can happen if you have previously installed a recent version of Brian 2 (version >= 2.1) and now are trying to import an older version directly from source, without installation. The exact fix depends on the details of how you installed things (e.g. with pip?) As a quick solution, you can delete the default_preferences file that is generated during installation (but not necessary for using Brian). E.g. search for it via:

$ locate brian2/default_preferences

**Comment by mstimberg** [comment] 2018-04-24 11:27
> Thank you very much.

I assume this means the issue is fixed for you? I'll close it, we can always reopen it if you still have problems.

**Closed by mstimberg** 2018-04-24 11:27 UTC

**Comment by xdzhangxuejun** [comment] 2018-04-25 13:54
I am sorry for that I given you a wrong think direction. My OS was broken a few days ago.I install the Brian2 successfully in the new OS.So, I do't  determine your advise is helpful  for me.I thank you for helping me whether it is useful to me or not.






At 2018-04-24 19:28:01, "Marcel Stimberg" <notifications@github.com> wrote:


Thank you very much.

I assume this means the issue is fixed for you? I'll close it, we can always reopen it if you still have problems.
