### ISSUE TITLE
[bug] connecting Neuron to Synapses with the _add_synapses_from_arrays function fails in cpp/cuda 

### ISSUE THREAD

**Issue by davideschiavone** [brian-team/brian2#1383] opened 2022-02-05 08:42 UTC
Dear all,

I want to connect a NeuronGroup to a Synapses object to produce Dopamine signals. 

I am running [this example](https://brian2.readthedocs.io/en/stable/examples/frompapers.Izhikevich_2007.html) taken from the Documentation to reproduce the Error. I pushed it [here](https://github.com/davideschiavone/SimpleMNIST/blob/main/Izhikevich2007/example.py).

Basically, if you pass to the [connect method](https://github.com/davideschiavone/SimpleMNIST/blob/main/Izhikevich2007/example.py#L115) two arrays, the function  `_add_synapses_from_arrays` refers to `len(group)` at line 1591. See [here](https://github.com/brian-team/brian2/blob/master/brian2/synapses/synapses.py#L1591).

This causes a check of a state variable when targeting a Synapses object, thus an Exception in cpp.

See the log:

```
DEBUG      Creating synapses from group 'spikegeneratorgroup' to group 'neurongroup', using pre-defined arrays) [brian2.synapses.synapses]
DEBUG      Creating synapses from group 'neurongroup' to group 'neurongroup', using pre-defined arrays) [brian2.synapses.synapses]
ERROR      Brian 2 encountered an unexpected error. If you think this is a bug in Brian 2, please report this issue either to the discourse forum at <http://brian.discourse.group/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /tmp/brian_debug_74agx1it.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/brian_script_jirvzjwq.py Thanks! [brian2]
Traceback (most recent call last):
  File "example.py", line 115, in <module>
    reward.connect(i=array_i, j=array_j)
  File "myhomefolder/anaconda3/envs/SimpleMNIST/lib/python3.8/site-packages/brian2/core/base.py", line 278, in device_override_decorated_function
    return func(*args, **kwds)
  File "myhomefolder/anaconda3/envs/SimpleMNIST/lib/python3.8/site-packages/brian2/synapses/synapses.py", line 1407, in connect
    self._add_synapses_from_arrays(i, j, n, p, namespace=namespace)
  File "myhomefolder/anaconda3/envs/SimpleMNIST/lib/python3.8/site-packages/brian2/synapses/synapses.py", line 1544, in _add_synapses_from_arrays
    if np.max(indices) >= len(group) or np.min(indices) < 0:
  File "myhomefolder/anaconda3/envs/SimpleMNIST/lib/python3.8/site-packages/brian2/groups/group.py", line 634, in __len__
    return int(self.variables['N'].get_value())
  File "myhomefolder/anaconda3/envs/SimpleMNIST/lib/python3.8/site-packages/brian2/core/variables.py", line 464, in get_value
    return self.device.get_value(self)
  File "myhomefolder/anaconda3/envs/SimpleMNIST/lib/python3.8/site-packages/brian2/devices/cpp_standalone/device.py", line 537, in get_value
    raise NotImplementedError('Cannot retrieve the values of state '
NotImplementedError: Cannot retrieve the values of state variables in standalone code before the simulation has been run.
```

I solved it by simply removing the check, i.e. commenting out the lines 1591 to 1596 of the [synapses.py file](https://github.com/brian-team/brian2/blob/master/brian2/synapses/synapses.py) 

However, this is a hack, and this should probably need to be solved properly :)
Just reporting it here.

**Comment by mstimberg** [comment] 2022-04-05 15:31
Thanks for the report, and sorry for the late reply. I will have to think about the best fix for this issue. In general we want to have a test there that the given indices are valid, but in standalone mode we cannot always know the number of synapses before the code runs (in particular, if the number of synapses is probabilistic). In that case we should probably just give a warning that we cannot check the indices.
In your example, the situation is a bit different, however: the synapses are created with `synapse_stdp.connect(i=0, j=1)`, so we *know* that there is exactly one synapse, even in standalone mode. We have a mechanism in place to deal with this in general. E.g. the following will lead to an error in standalone mode:
```Python
neurons = NeuronGroup(...)
neurons.v = 'rand()*mV'
print(neurons.v)  # error: do not know the values of v yet
```
but this will work
```Python
neurons = NeuronGroup(...)
neurons.v = -70*mV
print(neurons.v)  # we don't need to run C++ code to know the values of v
```
I'll try to figure out why this is not quite working as intended here.

**Comment by mstimberg** [comment] 2022-04-06 08:27
I just realized that I already opened an issue about this several years ago: #1028 ...

**Closed** 2022-06-06 18:25 UTC
Labels: bug, component: standalone, high priority, component: synapses
