### ISSUE TITLE
Check that Cython is running efficiently

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#421] opened 2015-03-05 13:45 UTC
In some recent benchmarks I found that the cython backend was running only slightly faster than the numpy backend in many cases. I guess something got messed up and it is falling back to Python. We should fix this, and also maybe add some tests that check that the generated Cython code doesn't fall back to Python. I think that this can be done programmatically?

**Comment by thesamovar** [comment] 2015-03-05 13:46
@rossant, you're my go-to Cython expert. Is there any way to check that a section of Cython code isn't falling back to Python automatically? (i.e. as part of a test suite)

**Comment by rossant** [comment] 2015-03-05 13:55
I don't know how to do that programmatically. However when using the IPython notebook, you can do:

```
%load_ext Cython

%%cython -a
some cython code...
```

and it will display your code with annotations, showing which lines fall back to CPython (= slowest) and which ones are efficiently compiled to C

see http://docs.cython.org/src/quickstart/cythonize.html#determining-where-to-add-types for example

**Comment by thesamovar** [comment] 2015-03-05 14:17
OK great. I can look at the source code for the Cython magic and work it out. Thanks!

**Comment by thesamovar** [comment] 2015-03-21 18:40
Just a note to myself. One quick way to check if it is dropping back to Python is to search for ``Py_DECREF`` and ``Py_GOTREF`` in the generated C++ code. Note that we'd only want to do this for code inside loops.

**Comment by thesamovar** [comment] 2015-10-27 17:06
Just runing the speed tests (which are not entirely comprehensive), Cython seems to be about the same for most tests. For the CUBA fixed connectivity test, it is quite slow though, so that needs looking into.

**Comment by thesamovar** [comment] 2015-10-27 23:15
OK, that's odd. On one computer, Cython runs much slower on the CUBA example, and on another one it runs faster. @mstimberg can you check it on yours? (To compare to what I did, just run CUBA twice with codegen set to cython and weave, and print the profile information on the second run.) The version of Cython on my two computers is different, but the newer version is the slower one (0.23 versus 0.21).

**Comment by thesamovar** [comment] 2015-10-27 23:47
I'm happy to call this closed I think. There doesn't appear to be any Python code creeping into the generated Cython code, so it's probably just variations on the type of C++ code that Cython generates compared to weave, which we don't have that much control over.

**Comment by mstimberg** [comment] 2015-10-28 09:21
I am seeing the same thing, CUBA is quite slow with Cython 0.23.3 but it is the same speed as weave (without fast compilation options) with Cython 0.22.1. Switching on fast compilation options makes a big difference for weave but none for Cython, I am not sure it is taken into account at all. I'll have a quick look whether there's anything we can do, maybe a default for an option changed in 0.23.

**Comment by mstimberg** [comment] 2015-10-28 11:08
I did not see anything obvious that explains the performance regression from 0.22 to 0.23. I had a quick look at the generated code in general, though, and there was one instance where a variable was used but not declared properly (the `_cond` variable in the thresholder), I added a commit that fixes this to the `cython_performance` branch. Looking at the annotated code, everything looks good, the only Python interaction is in specific lines where we resize things (monitors, synapses) and in the code where we get the values from the namespace dictionary. In the latter part, there seem to be at least two things that could be improved however:
* we get all the `Variable` objects from the namespace, but this is only very rarely needed and if then only for `DynamicVariable` objects (to resize them via Python). I am not sure whether it is worth having another template comment for this use case, but at least we could restrict it to `DynamicVariable` objects
* The size of arrays in the `_num_...` variable is dynamically determined with `len(...)` instead of putting in the known size directly into the code. The disadvantage of that would be that it will trigger a recompile if this number changed, so while we could do it for synapses, for example (since their number will stay constant over a run), this means that examples with stochastic connectivity like CUBA have to recompile some bits every time. But at least for all non-dynamic arrays (number of neurons mostly), this could be worth doing, right?

I don't think it is super-important but it is also easy to do. Should we maybe quickly implement those two changes in the `cython_performance` branch while we're at it and close this issue? Otherwise I'd be happy to keep this issue open but remove it from the 2.0 milestone.

**Comment by thesamovar** [comment] 2015-10-28 12:30
With fast compilation off were Cython and weave running at the same speed? If so, I guess that's the issue.

I don't think we need to optimise the ``_num_...`` variables since that's only called once. If the one-off costs were the problem, we'd see that Cython performance approached weave for large N but there's a fairly constant difference between them. So I'd say let's stick to the current approach to save recompiles. Similarly, I don't think we need to optimise which variables we get from the namespace, since it's only O(1) again.

**Comment by thesamovar** [comment] 2015-10-28 12:40
I would say we should have a new option (not for 2.0) saying that Cython 0.23 ignores compilation options and can we work around that. Then we can merge the cython performance branch and close this issue.

**Comment by mstimberg** [comment] 2015-10-28 12:48
> With fast compilation off were Cython and weave running at the same speed? If so, I guess that's the issue.

No, it does not seem to be that. These are the times (very rought, I only ran it twice for each configuration and took the second time) that I get for in the profiling information for `neurongroup_stateupdater` in the CUBA example:

optimisations? | weave | Cython 0.22 | Cython 0.23
-----------------|-----------------|-----------------|---------
*on* | 0.4s | 2.6s | 3.5s
*off* | 2.8s | 2.6s | 3.4s

So in general the optimisations do not seem to help in Cython (but they are used, I checked the gcc call), this is probably because there is more boilerplate code around stuff that prevents the compiler from applying optimisations. But there is also a clear performance regression from Cython 0.22 to 0.23. Maybe we can reduce it to a minimal example and file an issue with Cython?

You are probably right about the optimisations. I don't think we can always ignore constant overhead per time step, but I did a quick manual check in the CUBA example and it did not change anything noticeable here, so let's forget about it for now.

**Comment by thesamovar** [comment] 2015-10-28 17:38
Oh, you see a huge difference between weave and Cython. Mine was more like 1.5s with weave, 2s with Cython, not 0.4s to 2.6s. That seems to me like something we need to investigate if that's correct?

**Comment by mstimberg** [comment] 2015-10-28 18:30
I only see a big difference with `-march=native -Ofast` which makes a big difference for weave but none for Cython. Without those, weave is the same speed as Cython for 0.22 and it's 2.8s vs. 3.4s with Cython 0.23 -- so a clear difference but not too dramatic either.

**Comment by thesamovar** [comment] 2015-10-28 19:16
That's crazy though that you get such a huge difference between weave and Cython, or between weave with and without the optimisation options on. That's a jump of 0.4s to 2.8s or 7x faster. Normally even if you get the best SSE options on, your speed will only jump 1.5-2x faster. Are we sure there isn't something else going on here? Did you check the output in terms of raster plots and number of spikes?

I could get my weave time for the stateupdater down ot 0.3s only by turning off refractoriness. Here are my results:

```
MSVC, Win64, Cython 0.23.4

Refractoriness on
	Optimisations on:
	- Cython: 2.53s
	- weave: 2.04s
	Optimisations off:
	- Cython: 2.57s
	- weave: 2.19s

Refractoriness off
	Optimisations on:
	- Cython: 0.84s
	- weave: 0.30s
	Optimisations off:
	- Cython: 0.74s
	- weave: 0.30s
```

It could be that there are some compiler differences. MSVC will assume that you have SSE if you are building a 64 bit binary even if you don't specify any optimisations. Maybe gcc doesn't? That doesn't explain everything though.

**Comment by thesamovar** [comment] 2015-10-28 19:43
OK, one thing is that Cython will never be able to use vectorised instruction sets because pointers are not declared as restricted in the generated C++ code. As far as I can tell, there is no way to achieve this in Cython. However, that would only explain a speed jump of 1.5-2x I think, not 7x.

So the only thing I can guess is that gcc is doing something much cleverer than MSVC for weave. There are two possibilities that occur to me:

1. There is an if statement in the generated code that could stop the use of SSE instructions being used. However, replacing the if statement with an equivalent arithmetic expression with the boolean variable doesn't speed things up on my computer at least.
2. There are (with refractoriness on) 19 generated LIO constants. Many of these are simplifiable, e.g. ``_lio_const_3 = El - (El * exp(((- dt) * int_(0.0)) / taum))`` could be simplified to ``_lio_const_3=0`` and consequently any expression it's involved in can probably be simplified too. It could be that gcc is doing this and MSVC is not.

Unless we have another idea, I think it must be (2). This suggests to me that we should do simplification of LIO consts after all. What do you think?

**Comment by thesamovar** [comment] 2015-10-28 19:45
One more thing to add: apparently recent versions of gcc will assume "strict aliasing" at -O2 or -O3, in other words it will assume that pointers are restricted unless you say otherwise. So actually, Cython should be able to do as well as weave on your machine with a modern gcc and all compiler options set to their highest level of optimisation. So again, I don't really understand what's going wrong here.

**Comment by mstimberg** [comment] 2015-10-29 16:45
I don't quite understand what is going on, either. I did run things on my new office computer and I saw the same pattern (for some reason, results I had earlier this day on the same machine were much faster, but I think it has something to do with the CPU not getting up to full speed for short runs, longer runs more or less restored the previous performance). All runs were with refractory on and while I did not check the results in detail, they were at least reasonable from looking at the raster plots (total number of spikes stayed the same). The speed difference is due to the `-ffast-math` switch, it's not the `-march=native`.

I noticed something else that is surprising: the fast-math option only makes a big difference for weave, not for C++ standalone. In fact, the `neurongroup_stateupdater` code object executes much faster in weave with the compilation options than in standalone! The total simulation time is still shorter in C++ standalone, but the run seems to be completely dominated by the state update (96% according to the profiling summary). Maybe there is a small thing that prevents both standalone and Cython from doing a massive optimisation? Not quite sure what that could be, though...

**Comment by thesamovar** [comment] 2015-10-29 16:49
Could it be the definition of the int or exp functions is different? In one case it gets inlined, in the other it doesn't? Something like that?

**Comment by thesamovar** [comment] 2015-10-29 16:50
That could make sense actually, since the definition of functions is going to be in a different file for standalone but everything goes in one megafile for weave, so that actually makes it easier for the compiler to inline, maybe?

**Comment by mstimberg** [comment] 2015-10-29 17:17
I has certainly something to do with the `exp` function -- if I do "random interruption profiling" (http://stackoverflow.com/questions/375913/what-can-i-use-to-profile-c-code-in-linux/378024#378024), I mostly end up in the `exp` function for unoptimized weave and both optimized and unoptimized standalone. A difference in the code is that standalone contains explicit constants whereas weave contains variables, e.g.:
```C++
// standalone:
const double _lio_const_3 = (-0.049) - ((-0.049) * exp(((- dt) * int_(0.0)) / 0.02));
// weave:
const double _lio_const_3 = El - (El * exp(((- dt) * int_(0.0)) / taum));
```
I am not quite sure how this can help, though, it should rather be the opposite... (Not related to the current question, but it seems that directly putting the value `dt` in here should get rid of all the `exp` calls). The exp functions are included from the standard library in the same way in both cases, and `int_` is also present as an inlined function in the same file for both, so this should not be it.

**Comment by thesamovar** [comment] 2015-10-29 17:22
The LIO consts should only happen once per timestep though, so it shouldn't be those exp calls, but rather the ones inside the loop over neurons.

**Comment by mstimberg** [comment] 2015-10-29 17:51
Hah, I found the issue! The important difference is that we represent boolean variables as `bool` in weave but as `char` in standalone and Cython (at least for standalone because of #317). I manually changed the type of `not_refractory` in the generated standalone code and the runtime plummeted, for a 10s run the `neurongroup_stateupdater` now takes 0.8s instead of 18s... Without `-ffast-math` it still takes 14s, so this matches the behaviour we've seen in weave.

**Comment by thesamovar** [comment] 2015-10-29 19:07
Great! An explanation! Or at least, part of one. So why does char perform so much morse than bool? One possibility is that ``int_`` is defined differently for bool than for all other types. For bool it returns ``x?0:1`` and for other types it returns ``(bool)x``. One possible solution for us is to have a new ``boolint`` function that always returns ``x?0:1`` for all types, and use this. It's a bit ugly. Perhaps there's a better solution if we understand why it is that ``x?0:1`` is so much better than ``(bool)x``? It'll also be interesting to see if it helps with MSVC too.

**Comment by mstimberg** [comment] 2015-10-29 19:22
> Perhaps there's a better solution if we understand why it is that `x?0:1` is so much better than `(bool)x`?

It's seems to be indeed the difference in the `int_` function (you meant `(int)x` instead of `(bool)x`, I guess). If I add a special case to the `int_` definition:
```C++
        template<> inline int int_(char value)
        {
	        return value ? 1 : 0;
        }
```
then I see the dramatic speedup with `-ffast-math` on standalone as well. Maybe it is simply because the compiler sees in this case that there are only two possible return values. In the loop, there are only two calls to `exp`, both look like this:
```Python
exp(_lio_const_9 * ((_lio_const_10 + (_lio_const_11 * int_(not_refractory)))
```
With the knowledge that `int_` returns either 0 or 1, we can pull this completely out of the loop, calculate the two values and use an if within the loop to decide which value to use.

**Comment by thesamovar** [comment] 2015-10-29 19:35
Interesting. It doesn't make any difference for MSVC (I was just trying the same thing), but that's not too surprising that gcc could be smarter than MSVC. I think given all this that my original plan to improve the loop invariant constants is still good. There's no reason that the version with refractoriness should be any slower than the version without, I think. What might be easy to do would be to just do the following simplifications (rather than calling sympy):

1. Replace 0*x with 0, x+0 with x, 1*x with x, and a few simple things like that.
2. Evaluate any subexpression that only involves compile time constants, like exp(0) -> 1.
3. Any LIO constant that simplifies to a single value has that value inserted into any expressions that use it.
4. (Optionally) replace things like x-x with 0.

This process would be repeated on the code until no changes were detected. I think that wouldn't be too difficult to implement and would be worthwhile.

Thoughts?

**Comment by thesamovar** [comment] 2015-10-29 21:09
OK I did that simplification (and pushed it to the cython performance branch) but it still doesn't solve the problem in windows. I realised afterwards that this obviously wouldn't work: ``not_refractory`` and therefore ``int_(not_refractory)`` can't get pulled out. On the other hand, it did give a speed improvement, so (after testing) it might be worth keeping.

How about this for a solution? We define a new variable ``int_not_refractory = int(not_refractory)`` and use this instead of putting ``int(not_refractory)`` everywhere. That would probably make a good start on the problem. Beyond that, I think we would need to start introducing if statements into generated code as an alternative to the boolean handling in the LIO code. In other words, we'd end up generating code like:

```
if(not_refractory)
   v = ...;
else
   v = ...;
```

But this would require support for the if statement in code generation. We might want to add that in the future anyway, so maybe it's not so crazy.

**Comment by mstimberg** [comment] 2015-10-30 11:30
I agree that it would be good to have if-statements in abstract code in the long run. It's not entirely obivous to me how we'll integrate it into the current equations to abstract code workflow, though. Not quite sure about the `int_not_refractory` -- what would that change? I also did a quick test where I used sympy's `cse` function to pull out repeated subexpressions. It made the abstract code look like this:
```Python
not_refractory = (t - lastspike) > 0.005000
_CSE_0 = 1/taue
_CSE_1 = _CSE_0*dt
_CSE_2 = 1/taui
_CSE_3 = _CSE_2*dt
_CSE_4 = int(not_refractory)
_CSE_5 = _CSE_4/taum
_CSE_6 = _CSE_5*dt
_CSE_7 = exp(-_CSE_6)
_CSE_8 = _CSE_4*taue
_CSE_9 = -taum
_CSE_10 = exp(_CSE_6)
_CSE_11 = _CSE_4*taui
_ge = ge*exp(-_CSE_1)
_gi = gi*exp(-_CSE_3)
_v = -El*_CSE_7 + El + _CSE_11*gi*(_CSE_10 - exp(_CSE_3))*exp(-dt*(_CSE_2 + _CSE_5))/(_CSE_11 + _CSE_9) + _CSE_7*v + _CSE_8*ge*(_CSE_10 - exp(_CSE_1))*exp(-dt*(_CSE_0 + _CSE_5))/(_CSE_8 + _CSE_9)
ge = _ge
gi = _gi
v = _v
```
This in fact made things worse, gcc now no longer seems to be able to optimize the exp calls away with `-ffast-math`. I think in general we should be careful not too overdo the optimization here and leave it to the compiler if possible. We have to be careful not to introduce hard-to-debug errors into the simulation (trivial things like removing an addition of 0 are of course fine, but then the compiler will certainly figure that out as well, no?)

**Comment by thesamovar** [comment] 2015-10-30 12:37
Well it's OK to leave it to the compiler when the compiler is smart like gcc but not so much for MSVC it seems. ;) So far, I haven't been able to get runtimes down to an equivalent of what gcc manages with MSVC, and it seems to me a problem because the CUBA example seems to me likely to come up very frequently and it's taking 7x longer to run than it should. I'll keep thinking about possible solutions.

**Comment by mstimberg** [comment] 2015-10-30 12:57
Maybe you should use gcc on Windows, then :) Which reminds me, I always wanted to try to compile with icc and the mkl, maybe that's even better. But I agree that we should do something about this issue, the performance difference is too big to ignore. And while it won't change anything for MSVC, I think it would still be good to use `bool` for standalone and Cython and rather special case boolean variables for writing to work around for the issue in #317.

**Comment by thesamovar** [comment] 2015-10-30 12:58
OK new idea which shouldn't be too hard to implement I think (will try to get it done this afternoon).

We keep doing what we're currently doing, but in the loop invariant rewriting stage, we add optional information to statements. The optional information is: the simplified expression if ``boolean_var=False``, the simplified expression if ``boolean_var=True``, and the difference in expression complexity between the more complex of these two simplified expressions and the usual expression. This is added to the ``Statement`` object but can be entirely ignored by the code generator. Or, the code generator can replace with an if statement (or whatever it likes). So we'd then implement this if statement alternative for C++ and Cython but not for numpy. We also don't need to worry about introducing additional complexity to code generation because it's entirely optional if you want to support this.

Thoughts?

**Comment by thesamovar** [comment] 2015-10-30 13:00
Happy to use bool instead of char. I think in Cython that is problematic because it doesn't have a proper bool type, but I may be wrong (perhaps that was only true in older Cythons?).

**Comment by mstimberg** [comment] 2015-10-30 13:04
Sounds like a good plan. Maybe before that, could you just try to manually replace the `v = ...` stament in the generated CUDA standalone code with one that uses  `if (not_refractory) ...` and see whether this gives you (together with the MSVC equivalent of `-ffast-math`) the speed improvement I saw for gcc?



> I think in Cython that is problematic because it doesn't have a proper bool type, but I may be wrong (perhaps that was only true in older Cythons?).

Yes, I vaguely remember something like this as well. I'll have a look.

**Comment by thesamovar** [comment] 2015-10-30 13:47
Yes, that makes it run much faster.

I'm wondering now if rather than doing a lot of complicated simplification, we could support this better at the integration level. In other words, we solve the differential equations once with ``not_refractory=1`` and once with ``not_refractory=0`` and pass those (as options) to the code generation step. This has the possible advantage that an equation that might not be solvable by sympy for variable ``not_refractory`` becomes solvable, and also that the generated solution might be simpler. What do you think?

**Closed** 2015-11-27 16:41 UTC
Labels: bug, enhancement
