### ISSUE TITLE
Why HH neurons fire without any input?

### ISSUE THREAD

**Issue by tigerwlin** [brian-team/brian2#744] opened 2016-09-02 19:24 UTC
Hi All,

I am very new to Brian2, apologize if this is a naive or duplicate question. I am just trying this example online (http://brian2.readthedocs.io/en/2.0rc3/examples/COBAHH.html)

I made all the excitatory and inhibitory synapses to be 0, so no synaptic inputs, my neurons should stay at resting potentials right? But the neurons still spikes. I am confused about where the stimulus come from to make my neurons spike? Thank you so much if anyone can explain this to me.

Here is my code:
```python
from brian2 import *
import numpy as np
import hdf5storage
import os

# Parameters
area = 20000*umetre**2
Cm = (1*ufarad*cm**-2) * area
gl = (5e-5*siemens*cm**-2) * area

El = -60*mV
EK = -90*mV
ENa = 50*mV
g_na = (100*msiemens*cm**-2) * area
#g_na = (0*msiemens*cm**-2) * area
g_kd = (30*msiemens*cm**-2) * area
#g_kd = (0*msiemens*cm**-2) * area
VT = -63*mV
# Time constants
taue = 5*ms
taui = 10*ms
# Reversal potentials
Ee = 0*mV
Ei = -80*mV
we = 0*nS # 6*nS  # excitatory synaptic weight
wi = 0*nS #67*nS  # inhibitory synaptic weight

# The model
eqs = Equations('''
dv/dt = (gl*(El-v)+ge*(Ee-v)+gi*(Ei-v)-
         g_na*(m*m*m)*h*(v-ENa)-
         g_kd*(n*n*n*n)*(v-EK))/Cm : volt
dm/dt = alpha_m*(1-m)-beta_m*m : 1
dn/dt = alpha_n*(1-n)-beta_n*n : 1
dh/dt = alpha_h*(1-h)-beta_h*h : 1
dge/dt = -ge*(1./taue) : siemens
dgi/dt = -gi*(1./taui) : siemens
alpha_m = 0.32*(mV**-1)*(13*mV-v+VT)/
         (exp((13*mV-v+VT)/(4*mV))-1.)/ms : Hz
beta_m = 0.28*(mV**-1)*(v-VT-40*mV)/
        (exp((v-VT-40*mV)/(5*mV))-1)/ms : Hz
alpha_h = 0.128*exp((17*mV-v+VT)/(18*mV))/ms : Hz
beta_h = 4./(1+exp((40*mV-v+VT)/(5*mV)))/ms : Hz
alpha_n = 0.032*(mV**-1)*(15*mV-v+VT)/
         (exp((15*mV-v+VT)/(5*mV))-1.)/ms : Hz
beta_n = .5*exp((10*mV-v+VT)/(40*mV))/ms : Hz
''')

P = NeuronGroup(50, model=eqs, threshold='v>-20*mV', refractory=3*ms,
                method='exponential_euler')
Pe = P[:40]
Pi = P[40:]
Ce = Synapses(Pe, P, on_pre='ge+=we')
Ci = Synapses(Pi, P, on_pre='gi+=wi')
Ce.connect(p=0.1)
Ci.connect(p=0.1)

# Initialization
#P.v = 'El + (randn() * 5 - 5)*mV'
#P.ge = '(randn() * 1.5 + 4) * 10.*nS'
#P.gi = '(randn() * 12 + 20) * 10.*nS'
P.v = 'El'
P.ge = '0*nS'
P.gi = '0*nS'

# Record a few traces
M = StateMonitor(P, 'v', record=True)
run(10 * second, report='stdout')

#---------------------store connections--------------------------------
exN = len(Ce.i)
inN = len(Ci.i)
exConn = np.vstack((np.array(Ce.i)+1,np.array(Ce.j)+1,np.ones((1,exN))))
inConn = np.vstack((np.array(Ci.i)+41,np.array(Ci.j)+1,-1*np.ones((1,inN))))
Conn = np.hstack((exConn,inConn))
np.savetxt('network.txt', Conn.transpose(), delimiter=',', fmt='%d')
os.system("python transferConn.py 1")
#----------------------------------------------------------------------
hdf5storage.savemat('./tmp/test_neuron.mat', {'data': np.array(M.v[:,::10]).transpose(),'conn': Conn}, format='7.3')
```

**Comment by mstimberg** [comment] 2016-09-05 12:23
Hi. For questions like this it is better to write a mail to the list (which of course you did as well, I answered there). I'll close this issue as invalid, as this is not a bug in Brian.

**Closed by mstimberg** 2016-09-05 12:23 UTC
Labels: invalid

**Comment by tigerwlin** [comment] 2016-09-05 16:53
Sorry. Will post it there next time. Thanks!

Tiger
