### ISSUE TITLE
Support for float32 type

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#417] opened 2015-02-27 15:00 UTC
At the moment, setting `prefs.core.default_float_dtype = float32` works if you're in numpy mode but not any of the other modes (which make assumptions about doubles). Also, if you use the compiled `SpikeQueue` it doesn't work because it assumes `float64`. When we get round to addressing this, we should possibly include a new test configuration for Travis that checks everything using float32 as well as float64. (Maybe just one Python 2.x and one Python 3.x).

**Comment by mstimberg** [comment] 2015-02-27 15:48
For the `SpikeQueue`, I think we have two reasonable options:
1. Just don't allow float32 synaptic delays -- currently, the user cannot change the data type of the delays specificially, they are always assumed to be the "default" type so we could as well always have it be of float64 type. It doesn't change anything for simulation speed since delays will be converted before the simulation into integers. Also, `Clock.dt` is currently not user changeable (and I don't really see any advantage of doing it)
2. If we want to allow both float32 delays and float64 delays, then I think the best would be to have a `prepare_float32` and a `prepare_float64` method in `SpikeQueue`, we could then code generate the correct call.

**Comment by thesamovar** [comment] 2015-02-27 16:00
I like option 2 best. I think it's good to allow delays to be float32 because they are per-synapse which makes them one of the candidates for largest users of memory. Incidentally, for the same reason we might want to make the int variables be potentially of different dtypes. Generally speaking, a lot of our memory use is going to be in Synapses and at the moment we're using quite a lot of memory (I think it's around 40 bytes per synapse without any synaptic variables).

Can we not use templates with Cython? So that it automatically selects the right version based on the dtype?

**Comment by mstimberg** [comment] 2015-02-27 16:07
> Can we not use templates with Cython? So that it automatically selects the right version based on the dtype?

Ah right, we should probably be able to simply use Cython's fused types.

**Comment by thesamovar** [comment] 2015-02-27 16:21
Like that we could have support for different int types easily too.

**Comment by thesamovar** [comment] 2015-07-21 13:53
CNS meeting update: as a short term solution for 2.0, we should raise an error if you try to change the default dtype to float32, until it gets sorted.

**Comment by mstimberg** [comment] 2015-08-04 11:29
I'll leave this issue open (since we don't have float32 support yet) but remove the 2.0 milestone since the short-term fix is now in place (setting the default dtype to float32 will raise an error).

**Comment by denisalevi** [comment] 2018-03-09 17:34
Any plans of merging the `float32_support` branch @mstimberg ? I will update the brian2 version for brian2CUDA in the next days and would  be keen on those single precision floats.

**Comment by mstimberg** [comment] 2018-03-12 14:08
@denisalevi  Unfortunately the progress stalled on this branch... Its working fine, but still a few tests need to be updated because the reduced precision makes the test fail (in particular for doctests that test the string output). I'll hope to get back to it soon, but don't expect it to be merged this week...

**Comment by denisalevi** [comment] 2018-07-06 08:55
Hi :). Any progress on this front? I expect that we will need a single precision preference in the next week. Any chance this will be merged soon? Otherwise I would implement our own preference for now.

**Comment by mstimberg** [comment] 2018-07-06 13:18
We actually have a basic working version in the `float32_support` branch. The problem is that many tests are failing because of the reduced accuracy and it would be nice to have a somewhat principled approach to deal with this. Also, in principal we allow setting different dtypes for individual variables, and this is very poorly tested.

**Comment by thesamovar** [comment] 2018-07-06 13:32
I haven't thought carefully about testing but it feels like it should just be a matter of having one value of epsilon for double and another for float?

I'm also happy for us to officially not support different dtypes for different variables.

**Closed** 2018-08-29 12:54 UTC
Labels: bug, component: codegen, component: standalone, major feature
