### ISSUE TITLE
brian2 installing and running appear some error

### ISSUE THREAD

**Issue by wjx0914** [brian-team/brian2#1011] opened 2018-09-28 02:57 UTC
Error encountered with object named "statemonitor".
Object was created here (most recent call only, full details in debug log):
  File "example4.py", line 27, in <module>
    statemon = StateMonitor(group, 'v', record=True)
An error occurred when preparing an object. ValueError: Unknown code generation target:  numpy , should be  one of ['auto', 'cython', 'numpy', 'weave']

**Comment by mstimberg** [comment] 2018-10-09 16:37
Hi, sorry for the late reply... Do you still have this problem? If yes, can you update to the latest Brian version (2.2) and check again? The error message is quite odd and I haven't seen this problem before. Can you provide a [minimal example](https://stackoverflow.com/help/mcve) that reproduces it for you?

**Comment by mstimberg** [comment] 2018-12-03 14:40
@wjx0914 *ping* (see my previous comment)

**Comment by wjx0914** [comment] 2018-12-10 09:12
@mstimberg thank you. what's the difference  of installing between  Brian2 version (2.2）and other version ? I find the commands of their installing same from https://brian2.readthedocs.io/en/2.2/introduction/install.html

**Comment by mstimberg** [comment] 2018-12-10 14:16
There's no difference in installing, but if you installed Brian 2 before the release of Brian 2 you need to update it. If you installed with conda, use `conda update -c conda-forge brian2`, for pip use `pip install brian2 --upgrade` (or `pip install brian2 --upgrade --no-deps` to avoid also updating all dependencies).

**Comment by wjx0914** [comment] 2018-12-11 11:43
@mstimberg ,thanks. I have updated the Brian2 using "conda update -c conda-forge brian2".
Below is my  result of brian2.test(), that is false. Actually my previous test result is also false,but my procedure can  be still run except the error of running "brian2.plot(rate_monitors[name].t/b2.second, rate_monitors[name].rate, '.')". 
Why does  brian2.test() always occur the error ?  lookinig forword to your solution.
![image](https://user-images.githubusercontent.com/43661240/49798326-f6038d00-fd7c-11e8-902e-4e1f4e473fc2.png)

FAIL: brian2.tests.test_synapses.test_transmission_scalar_delay_different_clocks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/anaconda3/lib/python3.6/site-packages/brian2/tests/test_synapses.py", line 1046, in test_transmission_scalar_delay_different_clocks
    assert len(l) == 1, 'expected a warning, got %d' % len(l)
AssertionError: expected a warning, got 2

----------------------------------------------------------------------
Ran 232 tests in 61.638s

FAILED (SKIP=14, failures=4)
ERROR: 1/3 test suite(s) did not complete successfully (see above).
False

**Comment by wjx0914** [comment] 2018-12-12 02:36
the version of brian2 is 2.2 rather than 2.2.1 after  update brain2  using"conda update -c conda-forge brian2",  what's the matter between them. you means, though the result of  brian2.test() is False , does it not matter if all your test failures are about problems with warnings but no error ?
![image](https://user-images.githubusercontent.com/43661240/49842788-dbbac500-fdf7-11e8-8499-4195222e4a48.png)

**Comment by mstimberg** [comment] 2018-12-13 16:30
> @mstimberg,my version of brian2 is 2.2 rather than 2.2.1 after update brain2 using"conda update -c conda-forge brian2", what's the matter between them.

I think that means that some other package is holding back `brian2` from being installed. I guess you get an error if you try to do `conda install -c conda-forge brian2=2.2.1`? The error message should give you an idea of what the problem is.

> you means, though the result of brian2.test() is False , does it not matter if all your test failures are about problems with warnings but no error ?

Our test suite checks in a couple of places that warnings are raised (or not), as expected. When you combine Brian 2 < 2.2.1 with recent versions of Cython, you get a number of additional warnings which make these tests fail. These warnings are annoying but not a problem. Ideally you want of course to update Brian2, but alternatively downgrading Cython should also get rid of the warnings.

**Comment by mstimberg** [comment] 2019-02-04 15:49
I'm going to close this issue for now, feel free to re-open it if you still have the problem.

**Closed by mstimberg** 2019-02-04 15:49 UTC

**Comment by Trinity-wang** [comment] 2019-07-24 11:05
ValueError: Unknown code generation target: weave, should be  one of ['auto', 'cython', 'numpy']
I also have this problem , and  my version of brian2.  is  2.2.1.1.   
When I run the Example: float_32_64_benchmark.py,  the problem occur ,  and  i didn 't know why?

**Comment by mstimberg** [comment] 2019-08-05 15:51
> ValueError: Unknown code generation target: weave, should be one of ['auto', 'cython', 'numpy']
> I also have this problem , and my version of brian2. is 2.2.1.1.
> When I run the Example: float_32_64_benchmark.py, the problem occur , and i didn 't know why?

@Trinity-wang Your problem is unrelated to the OP's problem. You are running an example that runs benchmark for all code generation targets that Brian supports, but this includes the `weave` target which is only supported under Python 2.x. If you want to run this example under Python 3.x, you can exclude the `weave` target by removing it from the `targets = [...]` list defined in line 127. But note that this example was really only used for internal benchmarking, it is not a relevant example for neural modelilng.
