### ISSUE TITLE
Warn if threshold but no reset/refractoriness

### ISSUE THREAD

**Issue by thesamovar** [brian-team/brian2#1169] opened 2020-03-10 13:54 UTC
Normally this will be a mistake, and we could warn and point to the correct place in the docs.

**Comment by mstimberg** [comment] 2020-03-10 14:49
I mostly agree with the reasoning, but our general policy has been so far to only raise a warning if there is a way to get rid of it. There are a few legitimate use cases for thresholds without reset and refractoriness (most importantly something of the type `threshold='rand() < rate*dt'`) – what should the user do in this case to get rid of the warning? I don't think we want to force them to set a dummy reset/refractoriness, right?

**Comment by thesamovar** [comment] 2020-03-10 15:48
Good point. Not sure if it's worth it indeed. Although maybe it's OK to have a dummy reset/refractoriness in the case of doing something like random thresholds (which is certainly legitimate, but slightly unusual)? I don't have strong feelings about it so happy to drop it.

**Comment by mstimberg** [comment] 2020-03-10 15:52
Not sure either... Another option would be potentially to rather have an after run check (like our check for NaN/inf) and raise a warning if a cell spikes in two successive time steps? I think this would almost always be a bug, but then again I don't know what one could do to avoid this warning if it isn't.

**Comment by thesamovar** [comment] 2020-03-12 10:35
Some people use very long dt and then you might easily see two spike in successive time steps, so not sure that this works.

We could use the dummy reset/refractoriness (e.g. ``reset=''``) solution, but with the additional rule that we don't show the warning if ``'rand' in threshold``? Bit hacky, but covers the huge majority of cases like that.

**Comment by rohithvarma3000** [comment] 2021-01-09 06:08
Hello @thesamovar ,
I have gone through this problem. I think a dummy reset will do the job.
 Should this dummy reset be given in the __init__ function of the class NeuronGroup?

**Comment by thesamovar** [comment] 2021-01-11 15:39
Thanks for getting involved! I don't really have time to think about this at the moment because schools are closed in the UK and I'm suddenly doing a lot more childcare than I had anticipated for the next few weeks at least. Perhaps @mstimberg can look at this if he has time.

A quick think about this and I don't mind have a warning that you can remove by explicitly putting reset='' or reset=None (and we use a different value for the default value - or perhaps there's a smarter way to do that in Python 3 now).

**Comment by mstimberg** [comment] 2021-01-11 16:48
Thanks indeed for offering help on this. Based on our earlier discussion here is what I think we want to do in `NeuronGroup.__init__`:
1. check whether the `threshold` argument is set (i.e. different from its default `None`), *but* both `reset` and `refractory` are not set (i.e. use their default arguments `None` and `False`, respectively)
2. if this is the case, check whether the `threshold` string contains either `rand()` or `randn()` – if this is the case, carry on, nothing to worry about.
3. if this is *not* the case, raise a warning

For the warning, I'd suggest a wording along the lines of "The NeuronGroup '{self.name}' sets a threshold but neither reset or refractory condition. Did you forget either of those? If this was intended, set the reset argument to an empty string in order to avoid this warning."

**Comment by rohithvarma3000** [comment] 2021-01-11 17:04
Ok @mstimberg, I will work on this

**Comment by mstimberg** [comment] 2021-02-11 16:00
Closed via #1262

**Closed by mstimberg** 2021-02-11 16:00 UTC
Labels: easy, enhancement, low priority, suggested contributions
